In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("D:\AI_ML\Files\Housing.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [4]:
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [5]:
data['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [6]:
data['prefarea'].unique()

array(['yes', 'no'], dtype=object)

In [7]:
data['mainroad'].unique()

array(['yes', 'no'], dtype=object)

In [8]:
data['guestroom'].unique()

array(['no', 'yes'], dtype=object)

In [9]:
data['basement'].unique()

array(['no', 'yes'], dtype=object)

In [10]:
data['airconditioning'].unique()

array(['yes', 'no'], dtype=object)

In [11]:
data['hotwaterheating'].unique()

array(['no', 'yes'], dtype=object)

In [12]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [13]:
data['prefarea'] = data['prefarea'].apply(lambda x:1 if x=='yes' else 0)
data['hotwaterheating'] = data['hotwaterheating'].apply(lambda x:1 if x=='yes' else 0)
data['airconditioning'] = data['airconditioning'].apply(lambda x:1 if x=='yes' else 0)
data['basement'] = data['basement'].apply(lambda x:1 if x=='yes' else 0)
data['guestroom'] = data['guestroom'].apply(lambda x:1 if x=='yes' else 0)
data['mainroad'] = data['mainroad'].apply(lambda x:1 if x=='yes' else 0)

In [ ]:
order = ['unfurnished', 'semi-furnished', 'furnished']
my_encoder = OrdinalEncoder(categories= [order], dtype = int)
data['furnishingstatus'] = my_encoder.fit_transform(data[['furnishingstatus']])

In [38]:
data['furnishingstatus'].unique()

array([2, 1, 0])

In [15]:
import pickle
with open('encoder.pkl','wb') as file:
    pickle.dump(my_encoder,file)

In [16]:
data['furnishingstatus'].value_counts()

furnishingstatus
1    227
0    178
2    140
Name: count, dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    int32
dtypes: int32(1), int64(12)
memory usage: 53.4 KB


In [18]:
data.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 2  
1                 2  
2                 1  
3                 2  
4                 2

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model = LinearRegression()

In [21]:
input_data= data.drop(columns='price')
actual_label = data[['price']]

In [22]:
from sklearn.linear_model import SGDRegressor

In [23]:
batch_size = 32
sgd_reg = SGDRegressor(loss='squared_error')

sgd_reg.fit(input_data,actual_label)

c:\Users\HP\anaconda3\envs\AI_Learning\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor()

In [24]:
sgd_reg.get_params()

{'alpha': 0.0001,
 'average': False,
 'early_stopping': False,
 'epsilon': 0.1,
 'eta0': 0.01,
 'fit_intercept': True,
 'l1_ratio': 0.15,
 'learning_rate': 'invscaling',
 'loss': 'squared_error',
 'max_iter': 1000,
 'n_iter_no_change': 5,
 'penalty': 'l2',
 'power_t': 0.25,
 'random_state': None,
 'shuffle': True,
 'tol': 0.001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [25]:
model.fit(input_data,actual_label)

LinearRegression()

#### aaba chai hami yo model lai as a pickle file ma save garxam

In [26]:
import pickle
with open('house_price_model.pkl','wb') as file:
    pickle.dump(model,file)

In [27]:
with open('house_price_model.pkl','rb') as file:
    my_model = pickle.load(file)

In [28]:
with open('encoder.pkl','rb') as file:
    encoder = pickle.load(file)

In [29]:
my_model.intercept_

array([-324509.04986338])

In [30]:
my_model.coef_

array([[2.43906887e+02, 1.19474386e+05, 9.88888287e+05, 4.50391518e+05,
        4.23100741e+05, 2.98030507e+05, 3.57926360e+05, 8.72936027e+05,
        8.53633595e+05, 2.79785637e+05, 6.47055599e+05, 2.13187781e+05]])

In [31]:
input_data[55:59].to_csv('price_testing.csv',index=False)

In [35]:
test_data =pd.read_csv('price_testing.csv')
test_data.head()

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0   6000         3          1        2         1          0         0   
1  11440         4          1        2         1          0         1   
2   9000         4          2        4         1          1         0   
3   7680         4          2        4         1          1         0   

   hotwaterheating  airconditioning  parking  prefarea furnishingstatus  
0                0                1        1         0      unfurnished  
1                0                0        1         1   semi-furnished  
2                0                1        1         1        furnished  
3                0                1        1         0   semi-furnished

In [43]:
encoder.transform(test_data[['furnishingstatus']])


array([[0],
       [1],
       [2],
       [1]])

In [44]:
test_data.head()

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0   6000         3          1        2         1          0         0   
1  11440         4          1        2         1          0         1   
2   9000         4          2        4         1          1         0   
3   7680         4          2        4         1          1         0   

   hotwaterheating  airconditioning  parking  prefarea furnishingstatus  
0                0                1        1         0      unfurnished  
1                0                0        1         1   semi-furnished  
2                0                1        1         1        furnished  
3                0                1        1         0   semi-furnished

In [45]:
# my_model.predict(test_data)