<a href="https://colab.research.google.com/github/Em-Esh-Magar/AI-ML-Learning/blob/main/Torch/Torch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
a = torch.tensor(2., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [5]:
c=a*b
d = c*100
d,c

(tensor(1000., grad_fn=<MulBackward0>), tensor(10., grad_fn=<MulBackward0>))

In [6]:
d.grad_fn

In [7]:
a = torch.tensor([[7., 9.],
                  [8.,3.]])
b = torch.tensor([[2., 5.],
                  [4.,6.]])

In [8]:
a.mean()  # total ko mean

tensor(6.7500)

In [9]:
a.mean(dim=0)    # column ko mean

tensor([7.5000, 6.0000])

In [10]:
a.mean(dim=1)  # row bata ko mean

tensor([8.0000, 5.5000])

In [11]:
a*b

tensor([[14., 45.],
        [32., 18.]])

In [12]:
a@b    # For matrix multiplication

tensor([[50., 89.],
        [28., 58.]])

In [13]:
a.argmax(dim = 0)     # columns ma sab bhanda max value ko index.
# a ko 1st column ma max value 1 index ma xa ani 2nd column ko max value 0 index ma xa.

tensor([1, 0])

In [14]:
c =  a.flatten()
c

tensor([7., 9., 8., 3.])

In [15]:
a.argmax()   # argmax ley a ko value lai flatten garxa. ani aaba chai kata max value xa ta tesko index dinxa.

tensor(1)

In [22]:
a.device

device(type='cuda', index=0)

In [21]:
a = a.to('cuda')

In [ ]:
# .backwar()
# .zero_grad()
# step()